### PR TITLE
typing: use simpler syntax where possible

### PR DESCRIPTION
**Pull request by felixfontein**
See https://github.com/ansible-community/antsibull-core/pull/18#issuecomment-1340037669

I didn't change the files in antsibull_core.schemas since Pydantic needs runtime access to the type definitions.

I also didn't change `typing.Mapping` and friends to `collections.abc.Mapping` since it's more to type :)

### CODE REVIEW

**Comment by gotmax23** [comment]
> I didn't change the files in antsibull_core.schemas since Pydantic needs runtime access to the type definitions.

It's okay to use all of the new syntax at runtime except the `|` union operator that was only added in Python 3.10. The rest of it (type hinting generics) was added in Python 3.9 (our minimum supported Python version).

> I also didn't change typing.Mapping and friends to collections.abc.Mapping since it's more to type :)

`from collections.abc import Mapping` or even `from collections import abc as cabc` and `cabc.Mapping` / `cabc.MutableMapping` / ... isn't too bad IMO.

**Comment by felixfontein** [comment]
> > I didn't change the files in antsibull_core.schemas since Pydantic needs runtime access to the type definitions.
> 
> It's okay to use all of the new syntax at runtime except the `|` union operator that was only added in Python 3.10. The rest of it (type hinting generics) was added in Python 3.9 (our minimum supported Python version).

Do you know whether this works with all pydantic versions, or whether a certain minimum version is required?

**Comment by felixfontein** [comment]
> > I also didn't change typing.Mapping and friends to collections.abc.Mapping since it's more to type :)
> 
> `from collections.abc import Mapping` or even `from collections import abc as cabc` and `cabc.Mapping` / `cabc.MutableMapping` / ... isn't too bad IMO.

f8a1baf3229b95e380ea5817247e6e16d3f48f52

**Comment by gotmax23** [comment]
> Do you know whether this works with all pydantic versions, or whether a certain minimum version is required?

I don't think so.

**Comment by felixfontein** [comment]
Ok, I've adjusted the schema in a0ddbe6166ffa3c8e7a86648d5f48f7f84ebec1b as well.

**Review by gotmax23 — APPROVED** [review]
LGTM. I didn't check if anything was missed, but there were no mistakes in what I looked at.

**Comment by felixfontein** [comment]
@gotmax23 thanks for reviewing and merging!

**Pull request merged**
