### PR TITLE
Re-add doc_parsing_backend to library context

### PR DESCRIPTION
**Pull request by felixfontein**
This reverts parts of commit 81cd1287c9c6980c5cf376ac1b37fb681749b420 from #54, since it broke compatibility.

### CODE REVIEW

**Comment by felixfontein** [comment]
The antsibull compatibility test failure is unrelated. What fails is https://github.com/ansible-community/antsibull/blob/main/playbooks/nested-ansible-tests.yaml#L68. The way that test is run looks very wrong to me (it does not involve ansible-test) anyway.

**Comment by felixfontein** [comment]
Once this is merged, the other new PRs should be fine (except possibly this broken antsibull compatibility test which is unrelated to antsibull-core).

**Review by gotmax23 — APPROVED** [review]

**Comment by gotmax23** [comment]
Ah, wait. Do you want to mention the deprecation in the changelog?

**Comment by felixfontein** [comment]
Good point, added.

**Review by gotmax23 — APPROVED** [review]

**Comment by felixfontein** [comment]
@gotmax23 thanks for reviewing this!

**Comment by gotmax23** [comment]
Thanks for fixing this! I'm sorry for screwing up the tests :).

**Pull request merged**
