### PR TITLE
deprecate support for old ansible versions <6.0.0

### PR DESCRIPTION
**Pull request by gotmax23**
Relates: https://github.com/ansible-community/antsibull-core/issues/123

### CODE REVIEW

**Comment by felixfontein** [comment]
Instead of deprecating, it we should probably outright remove it. Ansible >= 6 means ansible-core >= 2.13, and the only known users of antsibull-core (antsibull and antsibull-docs) don't support ansible-core < 2.13 anymore. If someone else is using antsibull-core and needs these features, they can always restrict to `antsibull-core < 3.0.0`.

**Comment by gotmax23** [comment]
Ah, I meant to target this PR against stable-2.

**Comment by gotmax23** [comment]
Fixed

**Comment by felixfontein** [comment]
Looks good to me. Not sure whether we really need to explicitly deprecate this before removing it from v3 though.

**Pull request closed without merging**
